export const EGRESS_ERRORS = new Set(['EGRESS_NOT_READY','EGRESS_CHECK_FAILED','EGRESS_IP_MISMATCH']);
export const MULTILOGIN_ERRORS = new Set([
  'MULTILOGIN_NOT_CONFIGURED','MULTILOGIN_BUSY','MULTILOGIN_AGENT_IN_USE',
  'MULTILOGIN_AGENT_FAILED','MULTILOGIN_API_FAILED','MULTILOGIN_ENDPOINT_NOT_READY',
  'MULTILOGIN_PROFILE_FAILED',
]);
export const INFRA_ERRORS = new Set([...EGRESS_ERRORS,...MULTILOGIN_ERRORS]);
